spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1072765959643-unfqdrdj29l3f36q433qisgetd54kkbi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile