spring.application.name=travel

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true



# Thymeleaf 설정
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# 정적 리소스 허용 (Spring Boot 2.x, 3.x 모두 지원)
spring.web.resources.static-locations=classpath:/static/